apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: k8s-resources
  name: sample-daemonset
spec:
  selector:
    matchLabels:
      app: daemon-demo-app
  template:
    metadata:
      labels:
        app: daemon-demo-app
    spec:
      containers:
        - name: busybox-container
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            ["sh", "-c", "while true; do echo Hello Kubernetes; sleep 10; done"]
