apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-resources
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3 # If not this line, k8s will use default replicas = 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginxw
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "256m"
            requests:
              memory: "64Mi"
              cpu: "128m"
