apiVersion: v1
kind: Service
metadata:
  namespace: k8s-resources
  name: nginx-nodeport-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx # Must match the labels of the Deployment pods
  ports:
    - protocol: TCP
      port: 8013 # Port exposed by the Service
      targetPort: 80 # Port on which your nginx container is running
      nodePort: 30080 # Static port on Node IP for external access
  type: NodePort
